# Flipkart Product & Customer Review Analysis

In [59]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [60]:
import pandas as pd

path = r"C:\Users\anilr\OneDrive\Desktop\Flipkart Product & Customer Review Analysis\Dataset.csv"

df = pd.read_csv(path, encoding="latin1")

df.head()

C:\Users\anilr\AppData\Local\Temp\ipykernel_18140\2779519678.py:5: DtypeWarning: Columns (0: Rate) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding="latin1")

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...

In [61]:
df.shape

(363261, 5)

In [62]:
df.isna().sum()

Product_name      15
Price             16
Rate              16
Review            22
Summary         2022
dtype: int64

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  str
 1   Price         363245 non-null  str
 2   Rate          363245 non-null  object
 3   Review        363239 non-null  str
 4   Summary       361239 non-null  str
dtypes: object(1), str(4)
memory usage: 13.9+ MB

In [64]:
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce').astype(float)

In [65]:
df['Price'] = pd.to_numeric(
    df['Price'].str.replace(r'[^\d]', '', regex=True),
    errors='coerce'
)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  str
 1   Price         363242 non-null  float64
 2   Rate          363239 non-null  float64
 3   Review        363239 non-null  str
 4   Summary       361239 non-null  str
dtypes: float64(2), str(3)
memory usage: 13.9 MB

In [67]:
df.dtypes

Product_name        str
Price           float64
Rate            float64
Review              str
Summary             str
dtype: object

In [68]:
df['Product_name'] = df['Product_name'].fillna(df['Product_name'].mode()[0])
df['Product_name'].isna().sum()

np.int64(0)

In [69]:
df['Review'] = df['Review'].fillna(df['Review'].mode()[0])
df['Review'].isna().sum()

np.int64(0)

In [70]:
df['Summary'] = df['Summary'].fillna(df['Product_name'].mode()[0])
df['Summary'].isna().sum()

np.int64(0)

In [71]:
df['Price'] = df['Price'].fillna(df['Price'].mean())
df['Price'].isna().sum()

np.int64(0)

In [72]:
df['Rate'] = df['Rate'].fillna(df['Rate'].mean())
df['Rate'].isna().sum()

np.int64(0)

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363261 non-null  str
 1   Price         363261 non-null  float64
 2   Rate          363261 non-null  float64
 3   Review        363261 non-null  str
 4   Summary       363261 non-null  str
dtypes: float64(2), str(3)
memory usage: 13.9 MB

In [74]:
df.duplicated().sum()

np.int64(53999)

In [75]:
df.drop_duplicates(inplace=True)

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
print(df[df['Rate'] > 5])

Empty DataFrame
Columns: [Product_name, Price, Rate, Review, Summary]
Index: []

In [78]:
print(df['Rate'].describe())

count    309262.000000
mean          4.013378
std           1.378991
min           1.000000
25%           3.000000
50%           5.000000
75%           5.000000
max           5.000000
Name: Rate, dtype: float64

In [79]:
df

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.000000,5.00000,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.000000,4.00000,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.000000,5.00000,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.000000,5.00000,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.000000,4.00000,Nice product,A Good cooler by Crompton. The height of the c...
...,...,...,...,...,...
363252,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.000000,5.00000,Worth every penny,Very nice cream
363253,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.000000,5.00000,Great product,It's a nice product...thanks very much to Flip...
363254,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.000000,5.00000,Best in the market!,Thanks ???
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.000000,5.00000,Terrific,Thanks
363260,,4581.903494,4.07032,Wonderful,Bumtum Baby Pull-Up Diaper Pants Combo Pack - ...

In [80]:
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nSummary:")
print(df.describe(include='all'))

Shape: (309262, 5)

Missing values:
Product_name    0
Price           0
Rate            0
Review          0
Summary         0
dtype: int64

Duplicate rows:
0

Data types:
Product_name        str
Price           float64
Rate            float64
Review              str
Summary             str
dtype: object

Summary:
                                             Product_name          Price  \
count                                              309262  309262.000000
unique                                               1175            NaN
top     cello Pack of 18 Opalware Cello Dazzle Lush Fi...            NaN
freq                                                 6947            NaN
mean                                                  NaN    4754.945004
std                                                   NaN    8305.140587
min                                                   NaN       2.000000
25%                                                   NaN     484.000000
50%                                                   NaN    1995.000000
75%                                                   NaN    5390.000000
max                                                   NaN  101100.000000

                 Rate     Review Summary
count   309262.000000     309262  309262
unique            NaN       3841  165851
top               NaN  Wonderful    Good
freq              NaN      15455    9229
mean         4.013378        NaN     NaN
std          1.378991        NaN     NaN
min          1.000000        NaN     NaN
25%          3.000000        NaN     NaN
50%          5.000000        NaN     NaN
75%          5.000000        NaN     NaN
max          5.000000        NaN     NaN

In [81]:
df.head()

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Nice product,A Good cooler by Crompton. The height of the c...

In [82]:
print("Duplicate rows:", df.duplicated().sum())
print(df.dtypes)

Duplicate rows: 0
Product_name        str
Price           float64
Rate            float64
Review              str
Summary             str
dtype: object

In [83]:
# save the cvs file
df.to_csv("Flipkart_Product_cleaned_data_set.csv")